# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - release/*
    - refs/tags/*
  paths:
    include:
    - arm-helper/*
    - core/*
    - ingredient/*
    - system/*    
    - lerna.json
    - package.json

pr:
  branches:
    include:
    - master
    - release/*
    - refs/tags/*
  paths:
    include:
    - arm-helper/*
    - core/*
    - ingredient/*
    - system/*    
    - lerna.json
    - package.json

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: Docker@2
  displayName: Login to DockerHub
  inputs:
    command: Login
    containerRegistry: HCHBDockerHub

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'
    publishRegistry: 'useFeed'
    publishFeed: 'hchb-npm-public-registry'
    publishPackageMetadata: true
    verbose: true

- task: gulp@1
  displayName: GULP List Environment
  inputs:
    gulpFile: 'gulpfile.js' 
    targets: 'listenvironment'    
    workingDirectory: '$(System.DefaultWorkingDirectory)'        

- task: gulp@1
  displayName: GULP Build and Release
  inputs:
    gulpFile: 'gulpfile.js' 
    targets: 'build'    
    workingDirectory: '$(System.DefaultWorkingDirectory)'    
    arguments: --sonarToken '$(SonarQubeToken)'

- task: Docker@2
  displayName: Logout from DockerHub
  inputs:
    command: Logout
    containerRegistry: HCHBDockerHub