apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: test
  annotations:
    bake.tag/envcode: BDE0
    bake.tag/environment: Bill Dev Env
    bake.tag/region: East US
    bake.tag/recipe: kv-test
    bake.tag/package_version: 1.0.0
    bake.tag/bake_version: 0.5.1
    bake.tag/owner: ""
    bake.tag/ing_version: 0.1.96
    bake.tag/ingredient: "@azbake/ingredient-kubernetes"
    bake.tag/deployment_ts: 2020-02-19T00:46:33.750Z
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        bake.tag/envcode: BDE0
        bake.tag/environment: Bill Dev Env
        bake.tag/region: East US
        bake.tag/recipe: kv-test
        bake.tag/package_version: 1.0.0
        bake.tag/bake_version: 0.5.1
        bake.tag/owner: ""
        bake.tag/ing_version: 0.1.96
        bake.tag/ingredient: "@azbake/ingredient-kubernetes"
        bake.tag/deployment_ts: 2020-02-19T00:46:33.750Z
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80

---
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: test2
  annotations:
    bake.tag/envcode: BDE0
    bake.tag/environment: Bill Dev Env
    bake.tag/region: East US
    bake.tag/recipe: kv-test
    bake.tag/package_version: 1.0.0
    bake.tag/bake_version: 0.5.1
    bake.tag/owner: ""
    bake.tag/ing_version: 0.1.96
    bake.tag/ingredient: "@azbake/ingredient-kubernetes"
    bake.tag/deployment_ts: 2020-02-19T00:46:33.750Z
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        bake.tag/envcode: BDE0
        bake.tag/environment: Bill Dev Env
        bake.tag/region: East US
        bake.tag/recipe: kv-test
        bake.tag/package_version: 1.0.0
        bake.tag/bake_version: 0.5.1
        bake.tag/owner: ""
        bake.tag/ing_version: 0.1.96
        bake.tag/ingredient: "@azbake/ingredient-kubernetes"
        bake.tag/deployment_ts: 2020-02-19T00:46:33.750Z
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80

---
